parameters:
  environtName: 'default'
  resourceGroupName: 'rg-amazerrr-default'

stages:
- stage: ${{ parameters.environtName }}
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: windows-latest
    environment: ${{ parameters.environtName }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts: app'
            inputs:
              artifactName: app
              downloadPath: '$(System.DefaultWorkingDirectory)'

          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts: deploy'
            inputs:
              artifactName: deploy
              downloadPath: '$(System.DefaultWorkingDirectory)'

          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts: web'
            inputs:
              artifactName: web
              downloadPath: '$(System.DefaultWorkingDirectory)'
          
          - task: AzurePowerShell@4
            displayName: 'Azure PowerShell script: FilePath'
            inputs:
              azureSubscription: AzureDevSubscription
              ScriptPath: '$(System.DefaultWorkingDirectory)/deploy/deploy.ps1'
              ScriptArguments: '-ResourceGroupName ${{ parameters.resourceGroupName }} -AppRootFolder "../web/"'
              workingDirectory: '$(System.DefaultWorkingDirectory)/deploy'
              azurePowerShellVersion: LatestVersion
          
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Azure Functions App'
            inputs:
              azureSubscription: AzureDevSubscription
              appType: functionApp
              WebAppName: '$(Custom.WebAppName)'
              enableCustomDeployment: true
              DeploymentType: runFromZip
