@endpoint = http://localhost:7071

### Post test image
POST {{endpoint}}/api/ImageAnalyzer HTTP/1.1

< ./../test/unit/Amazerrr.Tests/Resources/Test1.png

### Post test file
POST {{endpoint}}/api/Solver HTTP/1.1

< ./Test1.txt
